FROM centos:7
RUN touch /etc/yum.repos.d/nginx.repo && echo -e '[nginx]\nname=nage repo\nbaseurl=http://nginx.org/packages/centos/7/$basearch/\ngpgcheck=0\nenabled=1' > /etc/yum.repos.d/nginx.repo
RUN yum -y install nginx
RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./product.conf /etc/nginx/conf.d/product.conf
COPY ./index.html /var/www/html/index.html
COPY ./smile.jpg /var/www/html/smile.jpg
COPY ./version /var/www/html/state/version
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]